apiVersion: v1
kind: Service
metadata:
  name: service-roll
  labels:
    app: lb

spec:
  selector:
    app: frontend
    
  type: LoadBalancer
  ports:
    - name: "http"
      port: 8080
      targetPort: 80