apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-first-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front1

  template:
    metadata:
      labels:
        app: front1
    spec:
      containers:
        - name: first-nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 6
          resources:
            limits:
              cpu: 100m
              memory: 96Mi