apiVersion: v1
kind: Pod
metadata:
  name: my-pod-nginx
  labels:
    app: my-app
    backend: mybackend
spec:
  containers:
    - name: my-container-nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /index.html
          initialDelaySeconds: 15
          port: 80
          failureThreshold: 1
          timeoutSeconds: 5
      readinessProbe:
        httpGet:
          path: /index.html
          port: 80
          initialDelaySeconds: 3
          failureThreshold: 3
          timeoutSeconds: 5