apiVersion: v1
kind: Service
metadata:
  name: first-service-app
  labels:
    tier: rp

spec:
  type: ClusterIP
  selector:
    app: front1
    
  ports:
    - name: http
      port: 8080
      targetPort: 80