apiVersion: v1
kind: Service
metadata:
  name: my-service-lb
  labels:
    app: rp
spec:
  type: LoadBalancer
  selector:
    app: front1
  ports:
    - name: http
      port: 8080
      targetPort: 80