apiVersion: v1
kind: Pod
metadata:
  name: my-pod-hostpath

spec:
  containers:
    - name: docker-container
      image: docker
      resources:
      command:
        - "sleep"
        - "100000"
      volumeMounts:
        - name: docker-vol
          mountPath: /var/run/docker.sock
  
  volumes:
    - name: docker-vol
      hostPath:
        path: /var/run/docker.sock
        type: Socket