apiVersion: v1
kind: Pod
metadata:
  name: my-pod-nginx
  labels:
    app: my-app
    backend: mybackend
spec:

  volumes:
    - name: mycm-vol
      configMap:
        name: my-cm-file
    - name: mysecret-vol
      secret:
        secretName: my-secret

  containers:
    - name: my-container-nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
      env:
        - name: FIRSTNAME
          valueFrom:
            configMapKeyRef:
              name: my-cm-env
              key: firstName

        - name: LASTNAME
          valueFrom:
            configMapKeyRef:
              name: my-cm-env
              key: lastName

        - name: HOBBIES
          valueFrom:
            configMapKeyRef:
              name: my-cm-env
              key: hobbies.name

        - name: DB_ROOT_PWD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: db-pwd

      envFrom:
        - configMapRef:
            name: my-cm-envs

      livenessProbe:
        httpGet:
          path: /index.html
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 1
      readinessProbe:
        httpGet:
          path: /50x.html
          port: 80
        periodSeconds: 2
        initialDelaySeconds: 3
        failureThreshold: 1
      resources:
        limits:
          cpu: 200m
          memory: 128Mi

      volumeMounts:
        - name: mycm-vol
          mountPath: /etc/app
        - name: mysecret-vol
          mountPath: /etc/app/confidentials
