apiVersion: v1
kind: Service
metadata:
  name: second-service-app
  labels:
    tier: rp
spec:
  type: ClusterIP
  selector:
    app: front2

  ports:
    - name: http2
      port: 8083
      targetPort: 80