apiVersion: v1
kind: Service
metadata:
  name: my-service-node-port
  labels:
    tier: rp

spec:
  type: NodePort
  selector:
    app: front2
  ports:
    - name: http-node
      port: 8082
      nodePort: 30000
      targetPort: 80