apiVersion: v1
kind: Pod
metadata:
  name: my-pod-nginx
  labels:
    app: my-app
    backend: mybackend
spec:
  containers:
    - name: my-container-nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
      env:
        - name: FIRSTNAME
          valueFrom:
            configMapKeyRef:
              name: my-simple-cm
              key: firstName

        - name: LASTNAME
          valueFrom:
            configMapKeyRef:
              name: my-simple-cm
              key: lastName

        - name: HOBBIES
          valueFrom:
            configMapKeyRef:
              name: my-simple-cm
              key: hobbies.name

      livenessProbe:
        httpGet:
          path: /index.html
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 1
      readinessProbe:
        httpGet:
          path: /50x.html
          port: 80
        periodSeconds: 2
        initialDelaySeconds: 3
        failureThreshold: 1
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
